name: Build Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        ./${{ env.VCPKG_INSTALLATION_ROOT }}/vcpkg.exe install portaudio:x64-windows
        ./${{ env.VCPKG_INSTALLATION_ROOT }}/vcpkg.exe install speexdsp:x64-windows
        cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_INSTALLATION_ROOT }}/scripts/buildsystems/vcpkg.cmake
        cmake --build build --config Release
        cp "${{ env.VCPKG_INSTALLATION_ROOT }}/installed/x64-windows/bin/*.dll" "build/Release"
    - uses: actions/upload-artifact@v7
      with:
        path: "build/Release"
